### ISSUE TITLE
Support VeChain

### ISSUE THREAD

**Issue by mirei83** [pwall-org/pwall#3]
Hey, this isnt an issue but I cant find a contact anywhere. 
I just wanted to ask if you could add vechain (https://github.com/vechain) to the list of supported coins. Its the same code as for ethereum (web3-eth-accounts.js) but it would be nice to see it listed as a seperate coin.

Thanks in advance

MiRei

**Comment by ghost** [comment]
Hi, sure I'll start working on it in a few minutes.

EDIT: It's done. VeChain was already supported but you can now use https://pwall.org/vechain to access it more easily.
