### ISSUE TITLE
Restore Qtum paper wallet

### ISSUE THREAD

**Issue by ghost** [pwall-org/pwall#6]
I have used your paper wallet generator and would like to restore it now. Your instruction is not really detailed and I´m quite new with Qtum. The generator is great! Can you give a detailed instruction how to restore the paper wallet with Qtum Core wallet? 

Thanks!

**Comment by shaun-19826** [comment]
Hello @Hampi0815 Are you still having this issue or your issue has been resolved ?

**Comment by ghost** [comment]
Hi -- You should check this with Qtum Core Wallet as Pwall only generates private and public keys. It does not handle deposits, withdrawals, etc.
